# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hp/sik

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hp/sik

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Only default component available"
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hp/sik/CMakeFiles /home/hp/sik//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hp/sik/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sikradio-receiver

# Build rule for target.
sikradio-receiver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sikradio-receiver
.PHONY : sikradio-receiver

# fast build rule for target.
sikradio-receiver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sikradio-receiver.dir/build.make CMakeFiles/sikradio-receiver.dir/build
.PHONY : sikradio-receiver/fast

#=============================================================================
# Target rules for targets named sikradio-sender

# Build rule for target.
sikradio-sender: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sikradio-sender
.PHONY : sikradio-sender

# fast build rule for target.
sikradio-sender/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sikradio-sender.dir/build.make CMakeFiles/sikradio-sender.dir/build
.PHONY : sikradio-sender/fast

sikradio-receiver.o: sikradio-receiver.c.o

.PHONY : sikradio-receiver.o

# target to build an object file
sikradio-receiver.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sikradio-receiver.dir/build.make CMakeFiles/sikradio-receiver.dir/sikradio-receiver.c.o
.PHONY : sikradio-receiver.c.o

sikradio-receiver.i: sikradio-receiver.c.i

.PHONY : sikradio-receiver.i

# target to preprocess a source file
sikradio-receiver.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sikradio-receiver.dir/build.make CMakeFiles/sikradio-receiver.dir/sikradio-receiver.c.i
.PHONY : sikradio-receiver.c.i

sikradio-receiver.s: sikradio-receiver.c.s

.PHONY : sikradio-receiver.s

# target to generate assembly for a file
sikradio-receiver.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sikradio-receiver.dir/build.make CMakeFiles/sikradio-receiver.dir/sikradio-receiver.c.s
.PHONY : sikradio-receiver.c.s

sikradio-sender.o: sikradio-sender.c.o

.PHONY : sikradio-sender.o

# target to build an object file
sikradio-sender.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sikradio-sender.dir/build.make CMakeFiles/sikradio-sender.dir/sikradio-sender.c.o
.PHONY : sikradio-sender.c.o

sikradio-sender.i: sikradio-sender.c.i

.PHONY : sikradio-sender.i

# target to preprocess a source file
sikradio-sender.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sikradio-sender.dir/build.make CMakeFiles/sikradio-sender.dir/sikradio-sender.c.i
.PHONY : sikradio-sender.c.i

sikradio-sender.s: sikradio-sender.c.s

.PHONY : sikradio-sender.s

# target to generate assembly for a file
sikradio-sender.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sikradio-sender.dir/build.make CMakeFiles/sikradio-sender.dir/sikradio-sender.c.s
.PHONY : sikradio-sender.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... sikradio-receiver"
	@echo "... sikradio-sender"
	@echo "... sikradio-receiver.o"
	@echo "... sikradio-receiver.i"
	@echo "... sikradio-receiver.s"
	@echo "... sikradio-sender.o"
	@echo "... sikradio-sender.i"
	@echo "... sikradio-sender.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

